### ISSUE TITLE
Plugin failed

### ISSUE THREAD

**Issue by t794104** [ctron/package-drone-jenkins#7]
I'm having trouble using the plug-in. I have the following options :
- server URL : http://obelix.service.cisnet:8080
- deploy key : fd4ea4747b5325bed9dd49b580a6e81e3c7e9640eaffbb20ebd3634e8100797f
- channel : test
- files to archive : *.rpm

with the 0.3.1 plug-in i get a failed without any error messages (very hard to debug). With 0.2.4 i get the following : 

Package Drone Server URL: http://obelix.service.cisnet:8080
ERROR: Step ‘Package Drone Deployer’ aborted due to exception: 
java.io.IOException: remote file operation failed: /opt/jenkins/workspace/APPcpnr-local-epots/label/RHEL6 at hudson.remoting.Channel@3d0bec70:nl-gv-ontw-fsip-dev42: java.io.IOException: Unable to serialize hudson.FilePath$FileCallableWrapper@1c54f53d
    at hudson.FilePath.act(FilePath.java:1014)
    at hudson.FilePath.act(FilePath.java:996)
    at de.dentrassi.pm.jenkins.DroneRecorder.perform(DroneRecorder.java:223)
    at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
    at hudson.model.Build$BuildExecution.post2(Build.java:185)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
    at hudson.model.Run.execute(Run.java:1766)
    at hudson.matrix.MatrixRun.run(MatrixRun.java:146)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:410)
Caused by: java.io.IOException: Unable to serialize hudson.FilePath$FileCallableWrapper@1c54f53d
    at hudson.remoting.UserRequest.serialize(UserRequest.java:201)
    at hudson.remoting.UserRequest.<init>(UserRequest.java:64)
    at hudson.remoting.Channel.call(Channel.java:779)
    at hudson.FilePath.act(FilePath.java:1007)
    ... 12 more
Caused by: java.io.NotSerializableException: org.apache.http.impl.client.DefaultHttpClient
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
    at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
    at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
    at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
    at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
    at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
    at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
    at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
    at hudson.remoting.UserRequest._serialize(UserRequest.java:190)
    at hudson.remoting.UserRequest.serialize(UserRequest.java:199)
    ... 15 more
Finished: FAILURE

I think there is a problem finding the file to archive.... but i have not idea what.

Jurgen

**Comment by ctron** [comment]
Which version of Jekins are you using?

**Comment by t794104** [comment]
The latest 2.7.2.

I think that for the 0.3.1 version the code fails on DroneRecord.java line 206 and exists without any warning. For 0.2.4 version (with out the check if the parameters are filled) it crashes as show on my previous post.

**Comment by ctron** [comment]
Hm I see. I never tried it with a 2.x release.

**Comment by t794104** [comment]
oke, i'm no java programmer... but how can i help ? do you need more info on my setup ? 

little background : i'm building a deployment setup where we use jenkins and it's new pipeline functions to build multiple projects, ending in rpm's. I want to use Package Drone (and your plugin) as repository system where from testing starts (also automated from jenkins).

So it would be nice if we could get this to work. 

And pointer for my java college too look at as help ?

**Comment by ctron** [comment]
I understand. Not realty since I haven't tried it out myself. To be honest, from that error log I don't know either what is wrong. I guess that plugin simply has to be ported over to 2.x.

Unfortunately I cannot make any promises right now. But I will try to solve it as soon as I can.

If you have someone who knows java, just check out the source of that GitHub repository and debug it.

**Comment by t794104** [comment]
Took me 2 evenings of staring at the code and adding debug println's to finaly see it ;

line 206 :        if ( validateStart ( run, listener ) )

if it is a valid start then exit with failure..... should be 'if ( ! validateStart ( run, listener ) )'
in the end it was a simple '!' that fixed it.

**Comment by ctron** [comment]
Damn. Can you make a change and a pull request?

**Comment by ctron** [comment]
And update (0.3.3) is pushed to Jenkins repositories. It may take a while until it is visible though.

Thanks for your help!

**Comment by t794104** [comment]
Right... i got it working on my local setup which is a single Jenkins Master. On our main setup it still gives me the error as in the original post. The difference is that our main uses multiple build node's and it doesn't build on the master... so back to debugging.

**Comment by t794104** [comment]
More reading ; the class UloadFiles if of the type MasterToSlaveFileCallable which implements FilePath.FileCallable (http://javadoc.jenkins-ci.org/hudson/FilePath.FileCallable.html). The doc say's 'Warning: implementations must be serializable, so prefer a static nested class to an inner class'. UploadFiles is not static... maybe it should ?

**Comment by t794104** [comment]
Right, took some time but i got it working. 

Test setup; Jenkins 2.19 master with 2 nodes. 
Goal : get packageDrone plugin working with a master/node setup using the new pipeline feature.

Because I'm no Java programmer I branched of the 0.2.4 tag as it's code is a lot simpler. Using https://jenkins.io/blog/2016/05/25/update-plugin-for-pipeline/ as guide i fixed the code.

So how do i continue ? can i push my 0.2.4-pipeline branch here so you guy's can look at it and see if / how it can be merged ?

**Comment by t794104** [comment]
Also first time GitHub users... i forked your project and added my 0.2.4-pipeline branch, Need to work on my commits and comments :)

**Comment by ctron** [comment]
Sorry for the delay .. really!

You can make a PR (pull request). See also: https://help.github.com/articles/about-pull-requests/

By doing that I can have a look and merge the code into this repository.

**Comment by t794104** [comment]
I forked the project and created a branche 0.2.x from tag 0.2.4. Apparently you can't create a pull request against a tag. And a pull request against the current master makes no cense. If you could create a branche 0.2.x in your repository i could create a pull request. 

PS : i already have a pull request against the master for fixes in 0.3.x but that request is only the pipeline stuff not the Master-Node stuff.

**Comment by ctron** [comment]
You could rebase on the master branch and then create a PR. That should be fine?!

**Comment by nfalco79** [comment]
this bug could be close
